version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam build
      - sam deploy --confirm-changeset
artifacts:
  files:
    - packaged-template.yml