version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam build
      - sam package --template-file template.yaml --output-template-file packaged-template.yml --s3-bucket microcenter-scraper-application
artifacts:
  files:
    - packaged-template.yml