AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  microsoft-stock-scraper

  Sample SAM Template for microsoft-stock-check

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MicrocenterStockScraper:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: microcenter-stock-scraper/
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies:
        - AmazonSNSFullAccess
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: 'rate(10 minutes)'
            Name: Scheduler
            Description: test schedule
            Enabled: True

